services:
  database:
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - path: .env
        required: true

volumes:
  mysql_data:
    driver: local
