-- CreateTable
CREATE TABLE `common_branch` (
    `BranchId` VARCHAR(100) NOT NULL,
    `BranchName` VARCHAR(100) NULL,
    `ShortBranchName2` INTEGER NULL,
    `BranchType` INTEGER NULL,
    `LocationStatus` INTEGER NULL,
    `BranchAddress` TEXT NULL,
    `PhoneNo` VARCHAR(100) NULL,
    `PhoneNoSMSGateway` VARCHAR(100) NULL,
    `Email` VARCHAR(100) NULL,
    `RootBranch` VARCHAR(100) NULL,
    `IsSPLD` TINYINT NULL,
    `ReceptionLeadTime` DOUBLE NULL,
    `ServiceLeadTime` DOUBLE NULL,
    `PartPickingLeadTime` DOUBLE NULL,
    `FinalInspectionLeadTime` DOUBLE NULL,
    `DocumentCheckingLeadTime` DOUBLE NULL,
    `InvoicingLeadTime` DOUBLE NULL,
    `CallCustomerNotificationLeadTime` DOUBLE NULL,
    `WashingLeadTime` DOUBLE NULL,
    `DeliveryLeadTime` DOUBLE NULL,
    `ClockOnLeadTime` DOUBLE NULL,
    `ClockOffLeadTime` DOUBLE NULL,
    `DADDataRange` INTEGER NULL,
    `DeadStock` INTEGER NULL,
    `DemandFrequency` INTEGER NULL,
    `DemandDuration` INTEGER NULL,
    `StockPolicyPriceLimit` DECIMAL(19, 0) NULL,
    `ReturnDaysLimit` INTEGER NULL,
    `ReturnPriceLimit` DECIMAL(19, 0) NULL,
    `BinningLimitDays` INTEGER NULL,
    `Region` VARCHAR(100) NULL,
    `TaxCodeOnSales` CHAR(36) NULL,
    `TaxCodeOnPurchase` CHAR(36) NULL,
    `WithHoldingTaxCode` CHAR(36) NULL,
    `IsRootBranch` TINYINT NULL,
    `DefaultPettyCashAccount` CHAR(36) NULL,
    `CashierStartingAmount` DECIMAL(19, 0) NULL,
    `CashierBalanceClear` TINYINT NULL,
    `DeadlinePeriodicService` INTEGER NULL,
    `MaximumReturnDownPayment` DOUBLE NULL,
    `ParentBranch` VARCHAR(100) NULL,
    `OptimisticLockField` INTEGER NULL,
    `GCRecord` INTEGER NULL,
    `DeliveryCode` VARCHAR(5) NULL,
    `PartInTransitAccount` CHAR(36) NULL,
    `ShortBranchNameDataTransfer` VARCHAR(4) NULL,
    `ShortBranchNameDataTransferOracle` VARCHAR(4) NULL,
    `ShortBranchName` VARCHAR(4) NULL,
    `ToyotaBranchCode` VARCHAR(100) NULL,
    `ToyotaBranchCodeAFI` VARCHAR(100) NULL,
    `ToyotaAuthorized` TINYINT NULL,
    `ParentToyotaBranchCode` VARCHAR(100) NULL,
    `PrincipalAuthorized` TINYINT NULL,
    `PrincipalBranchCode` VARCHAR(100) NULL,
    `ParentPrincipalBranchCode` VARCHAR(100) NULL,
    `DefaultLocation` CHAR(36) NULL,
    `DefaultIntransitLocation` CHAR(36) NULL,
    `OrganizationalUnitTypeForTransferRequest` INTEGER NULL,
    `Province` VARCHAR(50) NULL,
    `City` VARCHAR(50) NULL,
    `MatriksDR` INTEGER NULL,
    `OutlateCode` VARCHAR(10) NULL,
    `Counters` TINYINT NULL,
    `InitialBranch` CHAR(4) NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,

    INDEX `BranchId`(`BranchId`),
    INDEX `DefaultIntransitLocation`(`DefaultIntransitLocation`),
    INDEX `DefaultLocation`(`DefaultLocation`),
    INDEX `DefaultPettyCashAccount`(`DefaultPettyCashAccount`),
    INDEX `DeliveryCode`(`DeliveryCode`),
    INDEX `GCRecord`(`GCRecord`),
    INDEX `ParentBranch`(`ParentBranch`),
    INDEX `PartInTransitAccount`(`PartInTransitAccount`),
    INDEX `Region`(`Region`),
    INDEX `ShortBranchName2`(`ShortBranchName2`),
    INDEX `TaxCodeOnPurchase`(`TaxCodeOnPurchase`),
    INDEX `TaxCodeOnSales`(`TaxCodeOnSales`),
    INDEX `WithHoldingTaxCode`(`WithHoldingTaxCode`),
    PRIMARY KEY (`BranchId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `common_contactperson` (
    `Oid` CHAR(36) NOT NULL,
    `ContactPersonName` VARCHAR(100) NULL,
    `MobileNo` VARCHAR(100) NULL,
    `Email` VARCHAR(100) NULL,
    `Relationship` VARCHAR(100) NULL,
    `DefaultContact` TINYINT NULL,
    `VehicleUnit` CHAR(36) NULL,
    `OptimisticLockField` INTEGER NULL,
    `GCRecord` INTEGER NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,

    INDEX `Oid`(`Oid`),
    INDEX `VehicleUnit`(`VehicleUnit`),
    PRIMARY KEY (`Oid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `common_customer` (
    `Oid` CHAR(36) NOT NULL,
    `Salutation` CHAR(36) NULL,
    `FirstName` VARCHAR(100) NULL,
    `LastName` VARCHAR(100) NULL,
    `CustomerId` VARCHAR(100) NULL,
    `TaxRegistrationNo` VARCHAR(100) NULL,
    `Branch` VARCHAR(100) NULL,
    `CustomerAddress` TEXT NULL,
    `OfficeAddress` TEXT NULL,
    `PhoneNo` VARCHAR(100) NULL,
    `MobileNo` VARCHAR(100) NULL,
    `DateOfBirth` DATE NULL,
    `PlaceOfBirth` VARCHAR(100) NULL,
    `IdentificationType` CHAR(36) NULL,
    `IdentificationNo` VARCHAR(100) NULL,
    `Religion` CHAR(36) NULL,
    `ContactSource` CHAR(36) NULL,
    `Occupation` CHAR(36) NULL,
    `CustomerType` VARCHAR(50) NULL,
    `Gender` VARCHAR(40) NULL,
    `RetailFleet` VARCHAR(191) NULL,
    `Email` VARCHAR(50) NULL,
    `Country` CHAR(5) NULL,
    `Province` INTEGER NULL,
    `City` INTEGER NULL,
    `District` INTEGER NULL,
    `SubDistrict` INTEGER NULL,
    `PostalCode` CHAR(10) NULL,
    `RT` CHAR(4) NULL,
    `RW` CHAR(4) NULL,
    `SIMCardNo` VARCHAR(50) NULL,
    `MarriedStatus` CHAR(3) NULL,
    `IncomePerMonth` DECIMAL(11, 0) NULL,
    `ExpensesPerMonth` DECIMAL(11, 0) NULL,
    `Hobby` VARCHAR(40) NULL,
    `Referensi` VARCHAR(100) NULL,
    `FavoriteFood` VARCHAR(40) NULL,
    `FavoriteDrink` VARCHAR(40) NULL,
    `BusinessFields` VARCHAR(100) NULL,
    `RegisteredDate` DATETIME(0) NULL,
    `VehiclePhoneNo` VARCHAR(100) NULL,
    `VehicleRelationship` VARCHAR(100) NULL,
    `VehicleUsers` VARCHAR(100) NULL,
    `VATEnabled` BOOLEAN NULL,
    `InActive` BOOLEAN NULL,
    `ReasonActivation` VARCHAR(255) NULL,
    `AppInActive` TINYINT NULL,
    `GCRecord` VARCHAR(11) NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,

    UNIQUE INDEX `IdentificationNo`(`IdentificationNo`),
    INDEX `Branch`(`Branch`),
    INDEX `ContactSource`(`ContactSource`),
    INDEX `IdentificationType`(`IdentificationType`),
    INDEX `Occupation`(`Occupation`),
    INDEX `Oid`(`Oid`),
    INDEX `Religion`(`Religion`),
    INDEX `Salutation`(`Salutation`),
    PRIMARY KEY (`Oid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `common_dealer` (
    `Oid` CHAR(36) NOT NULL,
    `DealerName` VARCHAR(100) NULL,
    `DealerType` TINYINT NULL,
    `Branch` VARCHAR(20) NULL,
    `OptimisticLockField` INTEGER NULL,
    `GCRecord` INTEGER NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,

    INDEX `Oid`(`Oid`),
    PRIMARY KEY (`Oid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `csv_jobs` (
    `id` VARCHAR(100) NOT NULL,
    `status` VARCHAR(20) NOT NULL,
    `params` TEXT NOT NULL,
    `fileName` VARCHAR(255) NOT NULL,
    `filePath` TEXT NOT NULL,
    `fileSize` BIGINT NULL,
    `error` TEXT NULL,
    `user_created` INTEGER NOT NULL,
    `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `deleted_at` DATETIME(0) NULL,

    INDEX `idx_created_at`(`created_at`),
    INDEX `idx_deleted_at`(`deleted_at`),
    INDEX `idx_user_created`(`user_created`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sales_vehiclebrand` (
    `Oid` CHAR(36) NOT NULL,
    `BrandName` VARCHAR(100) NULL,
    `GCRecord` INTEGER NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,

    INDEX `Oid`(`Oid`),
    PRIMARY KEY (`Oid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sales_vehiclecolor` (
    `Oid` CHAR(36) NOT NULL,
    `ColorCode` VARCHAR(100) NULL,
    `Description` VARCHAR(100) NULL,
    `ColorNameEn` VARCHAR(100) NULL,
    `ColorNameId` VARCHAR(100) NULL,
    `GCRecord` INTEGER NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,

    INDEX `ColorCode`(`ColorCode`),
    INDEX `ColorNameId`(`ColorNameId`),
    INDEX `Oid`(`Oid`),
    PRIMARY KEY (`Oid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sales_vehiclefullmodel` (
    `VehicleFullModelId` CHAR(36) NOT NULL,
    `ToyotaFullModelId` VARCHAR(100) NULL,
    `FullModelId` VARCHAR(100) NULL,
    `VehicleFullModelName` VARCHAR(100) NULL,
    `VehicleModel` CHAR(36) NULL,
    `ReleasedYear` DATETIME(0) NULL,
    `FuelType` CHAR(36) NULL,
    `isDifferentPriceByColor` TINYINT NULL,
    `CylinderVolume` CHAR(36) NULL,
    `Discontinue` TINYINT NULL,
    `Brand` CHAR(36) NULL,
    `GCRecord` INTEGER NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,

    INDEX `ToyotaFullModelId`(`ToyotaFullModelId`),
    INDEX `ToyotaFullModelId_2`(`ToyotaFullModelId`),
    INDEX `VehicleFullModelId`(`VehicleFullModelId`),
    INDEX `VehicleModel`(`VehicleModel`),
    PRIMARY KEY (`VehicleFullModelId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sales_vehiclemodel` (
    `Oid` CHAR(36) NOT NULL,
    `VehicleModelName` VARCHAR(100) NULL,
    `Photo` VARCHAR(100) NULL,
    `SalesPoint` DOUBLE NULL,
    `Brand` CHAR(36) NULL,
    `Design` VARCHAR(50) NULL,
    `Category` VARCHAR(50) NULL,
    `Sub_Category` VARCHAR(50) NULL,
    `Price` VARCHAR(50) NULL,
    `Sub_Price` VARCHAR(50) NULL,
    `Discontinue` BOOLEAN NULL,
    `GCRecord` INTEGER NULL,
    `VehicleGroupModel` CHAR(36) NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,

    UNIQUE INDEX `VehicleModelName`(`VehicleModelName`),
    INDEX `Oid`(`Oid`),
    PRIMARY KEY (`Oid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sales_vehicleunit` (
    `ActiveServiceBooking` CHAR(36) NULL,
    `DefaultContact` CHAR(36) NULL,
    `Oid` CHAR(36) NOT NULL,
    `RRN` VARCHAR(100) NULL,
    `VinCode` VARCHAR(100) NULL,
    `VehicleRegistrationNumber` VARCHAR(100) NULL,
    `RegistrationDate` DATETIME(0) NULL,
    `RegistrationExpiryDate` DATETIME(0) NULL,
    `EngineSerialNo` VARCHAR(100) NULL,
    `FrameSerialNo` VARCHAR(100) NULL,
    `WMI` CHAR(5) NULL,
    `VDS` CHAR(10) NULL,
    `CD` CHAR(5) NULL,
    `VIS` CHAR(20) NULL,
    `VehicleModel` CHAR(36) NULL,
    `VehicleFullModel` CHAR(36) NULL,
    `Color` CHAR(36) NULL,
    `LicensePlateNumber` VARCHAR(100) NULL,
    `VehicleDeliveryDate` DATETIME(0) NULL,
    `ApplicationForInvoiceDate` DATETIME(0) NULL,
    `ProductionYear` INTEGER NULL,
    `TWC` DATETIME(0) NULL,
    `DailyAverageMileage` INTEGER NULL,
    `LastMileageRecord` INTEGER NULL,
    `LastServiceDate` DATETIME(0) NULL,
    `ExpectedNextServiceDate` DATETIME(0) NULL,
    `NextServiceMileage` INTEGER NULL,
    `NextService` CHAR(36) NULL,
    `RegistrationType` INTEGER NULL,
    `FieldAction` TINYINT NULL,
    `FieldActionName` CHAR(36) NULL,
    `PassiveCustomer` TINYINT NULL,
    `Blacklisted` TINYINT NULL,
    `Branch` VARCHAR(100) NULL,
    `VehicleNo` VARCHAR(100) NULL,
    `KeyNo` VARCHAR(100) NULL,
    `Dealer` CHAR(36) NULL,
    `VehicleProduct` CHAR(36) NULL,
    `Customer` CHAR(36) NULL,
    `Partner` CHAR(36) NULL,
    `Leasing` CHAR(36) NULL,
    `SalesRemark` LONGTEXT NULL,
    `SalesName` VARCHAR(100) NULL,
    `TestDriveUnitStock` CHAR(36) NULL,
    `VehicleOrder` CHAR(36) NULL,
    `Route` CHAR(36) NULL,
    `LatestLocation` CHAR(36) NULL,
    `Insurance` CHAR(36) NULL,
    `InsuranceType` CHAR(36) NULL,
    `RateInsurance` INTEGER NULL,
    `InsuranceValue` DECIMAL(19, 0) NULL,
    `Tenor` INTEGER NULL,
    `TenorType` CHAR(5) NULL,
    `ExpectedNextServiceByMilage` INTEGER NULL,
    `PeriodicServiceDeadline` DATETIME(0) NULL,
    `CalculatedService` DATETIME(0) NULL,
    `OptimisticLockField` INTEGER NULL,
    `GCRecord` INTEGER NULL,
    `ServiceRemark` LONGTEXT NULL,
    `PolisNo` VARCHAR(100) NULL,
    `Queue` VARCHAR(36) NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,
    `InsuranceExpireDate` DATETIME(0) NULL,
    `PaymentMethod` CHAR(50) NULL,

    INDEX `ActiveServiceBooking`(`ActiveServiceBooking`),
    INDEX `Branch`(`Branch`),
    INDEX `Customer`(`Customer`),
    INDEX `Dealer`(`Dealer`),
    INDEX `DefaultContact`(`DefaultContact`),
    INDEX `FieldActionName`(`FieldActionName`),
    INDEX `FrameSerialNo`(`FrameSerialNo`),
    INDEX `GCRecord`(`GCRecord`),
    INDEX `Insurance`(`Insurance`),
    INDEX `LatestLocation`(`LatestLocation`),
    INDEX `Leasing`(`Leasing`),
    INDEX `NextService`(`NextService`),
    INDEX `Oid`(`Oid`),
    INDEX `Partner`(`Partner`),
    INDEX `Route`(`Route`),
    INDEX `TestDriveUnitStock`(`TestDriveUnitStock`),
    INDEX `VehicleOrder`(`VehicleOrder`),
    INDEX `VehicleProduct`(`VehicleProduct`),
    PRIMARY KEY (`Oid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `service_insurance` (
    `Oid` CHAR(36) NOT NULL,
    `InsuranceName` VARCHAR(100) NULL,
    `NPWP` VARCHAR(100) NULL,
    `PhoneNo` VARCHAR(100) NULL,
    `Email` VARCHAR(100) NULL,
    `Address` VARCHAR(255) NULL,
    `CreditLimit` DECIMAL(19, 0) NULL,
    `CreditAmount` DECIMAL(19, 0) NULL,
    `ContactPersonName` CHAR(36) NULL,
    `ContactPersonPhone` CHAR(15) NULL,
    `DiscountForInsurer` DOUBLE NULL,
    `ReceivableAccount` CHAR(36) NULL,
    `OptimisticLockField` INTEGER NULL,
    `GCRecord` INTEGER NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,
    `TermOfPayment` INTEGER NULL,

    INDEX `Oid`(`Oid`),
    PRIMARY KEY (`Oid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `service_invoice` (
    `Oid` CHAR(36) NOT NULL,
    `Invoice` VARCHAR(5) NULL,
    `InvoiceNo` VARCHAR(50) NULL,
    `InvoiceNoSoa` VARCHAR(50) NULL,
    `BilledTo` CHAR(36) NULL,
    `InvoiceDate` DATETIME(0) NULL,
    `Branch` VARCHAR(100) NULL,
    `TaxRegistrationNo` VARCHAR(100) NULL,
    `WorkOrder` CHAR(36) NULL,
    `TermOfPayment` INTEGER NULL,
    `BillingStaff` CHAR(36) NULL,
    `TotalJob` DECIMAL(19, 0) NULL,
    `TotalPart` DECIMAL(19, 0) NULL,
    `Stamp` CHAR(36) NULL,
    `Tax` DECIMAL(19, 0) NULL,
    `InvoiceAmount` DECIMAL(19, 0) NULL,
    `InvoiceAmountReport` DECIMAL(19, 0) NULL DEFAULT 0,
    `TotalPayment` DECIMAL(19, 0) NULL DEFAULT 0,
    `InvoiceStatus` BOOLEAN NULL DEFAULT true,
    `IncludeDutyStamp` TINYINT NULL,
    `Sequence` BIGINT NULL,
    `IsPosted` TINYINT NULL,
    `Remark` TEXT NULL,
    `CNDate` DATETIME(0) NULL,
    `ClaimNumber` VARCHAR(50) NULL,
    `OptimisticLockField` INTEGER NULL,
    `GCRecord` INTEGER NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,

    INDEX `BilledTo`(`BilledTo`),
    INDEX `Branch`(`Branch`),
    INDEX `CNDate`(`CNDate`),
    INDEX `Invoice`(`Invoice`),
    INDEX `InvoiceAmount`(`InvoiceAmount`),
    INDEX `InvoiceDate`(`InvoiceDate`),
    INDEX `InvoiceNoSoa`(`InvoiceNoSoa`),
    INDEX `InvoiceStatus`(`InvoiceStatus`),
    INDEX `Oid`(`Oid`),
    INDEX `TotalPayment`(`TotalPayment`),
    INDEX `WorkOrder`(`WorkOrder`),
    PRIMARY KEY (`Oid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `service_joborder` (
    `WorkOrder` CHAR(36) NULL,
    `Job` CHAR(36) NULL,
    `CustomJobDescription` VARCHAR(100) NULL,
    `IsReturnJob` TINYINT NULL,
    `SPKApproved` TINYINT NULL,
    `FinalInspectionUnSolvedJob` TINYINT NULL,
    `FinalInspectionJobSolvedBy` CHAR(36) NULL,
    `Technician` CHAR(36) NULL,
    `Stall` CHAR(36) NULL,
    `JobServiceRate` DOUBLE NULL,
    `TechnicianJobRate` DOUBLE NULL,
    `ServiceUnitPrice` DECIMAL(19, 0) NULL,
    `WithholdingTax` CHAR(36) NULL,
    `VATCode` CHAR(36) NULL,
    `Program` CHAR(36) NULL,
    `DiscountType` CHAR(36) NULL,
    `ProgramPercentage` DOUBLE NULL,
    `ProgramName` CHAR(36) NULL,
    `ProgramAmount` DECIMAL(19, 0) NULL,
    `Partner` CHAR(36) NULL,
    `DiscountForPartner` DOUBLE NULL,
    `DiscountApproved` TINYINT NULL,
    `Discount` CHAR(36) NULL,
    `DiscountName` CHAR(36) NULL,
    `DiscountPercentage` DOUBLE NULL,
    `Insurance` CHAR(36) NULL,
    `DiscountForInsurer` DOUBLE NULL,
    `InsuranceName` CHAR(36) NULL,
    `PartnerStatus` INTEGER NULL,
    `FinishTime` DATETIME(0) NULL,
    `EstimatedFinishTime` DATETIME(0) NULL,
    `ServiceStartOn` DATETIME(0) NULL,
    `ActualServiceRate` DOUBLE NULL,
    `RequirePO` TINYINT NULL,
    `JobStatus` INTEGER NULL,
    `IsActive` TINYINT NULL,
    `SubletInvoiceCreated` TINYINT NULL,
    `Billed` TINYINT NULL,
    `ProgramBilled` TINYINT NULL,
    `AllDay` TINYINT NULL,
    `EndOn` DATETIME(0) NULL,
    `Label` INTEGER NULL,
    `Location` VARCHAR(100) NULL,
    `Status` INTEGER NULL,
    `Type` INTEGER NULL,
    `OptimisticLockField` INTEGER NULL,
    `GCRecord` INTEGER NULL,
    `TotalJobReDo` INTEGER NULL,
    `ServiceInvoice` CHAR(36) NULL,
    `IsJobReDo` TINYINT NULL,
    `JobReDoCount` TINYINT NULL DEFAULT 0,
    `JobOrderId` CHAR(36) NOT NULL,
    `JobInsuranceAmount` DECIMAL(19, 0) NULL,
    `ExcludeInLeadTimeCalc` TINYINT NULL,
    `FieldAction` CHAR(36) NOT NULL,
    `RemarkRedo` TEXT NULL,
    `FieldTemporaty` TEXT NULL,
    `InvJobDate` DATETIME(0) NULL,
    `Invoice` CHAR(5) NULL,
    `IivJobDate` DATETIME(0) NULL,
    `InsuranceInvoice` CHAR(5) NULL,
    `PivJobDate` DATETIME(0) NULL,
    `ProgramInvoice` CHAR(5) NULL,
    `JobTAM` VARCHAR(255) NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,
    `SubletVendorPrice` DECIMAL(10, 0) NULL,

    INDEX `Discount`(`Discount`),
    INDEX `FinalInspectionJobSolvedBy`(`FinalInspectionJobSolvedBy`),
    INDEX `GCRecord`(`GCRecord`),
    INDEX `Insurance`(`Insurance`),
    INDEX `Job`(`Job`),
    INDEX `Program`(`Program`),
    INDEX `ServiceInvoice`(`ServiceInvoice`),
    INDEX `Stall`(`Stall`),
    INDEX `Technician`(`Technician`),
    INDEX `VATCode`(`VATCode`),
    INDEX `WithholdingTax`(`WithholdingTax`),
    INDEX `WorkOrder`(`WorkOrder`),
    INDEX `deleted_at`(`deleted_at`),
    PRIMARY KEY (`JobOrderId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `service_mobileservicetype` (
    `Oid` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `Description` VARCHAR(100) NULL,
    `OptimisticLockField` INTEGER NULL,
    `GCRecord` INTEGER NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,

    INDEX `Oid`(`Oid`),
    PRIMARY KEY (`Oid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `service_program` (
    `Oid` CHAR(36) NOT NULL,
    `ProgramName` VARCHAR(100) NULL,
    `ValidFrom` DATE NULL,
    `ValidThru` DATE NULL,
    `DiscountType` CHAR(36) NULL,
    `ProgramValueType` CHAR(36) NULL,
    `PercentageValue` DOUBLE NULL,
    `AmountValue` DECIMAL(19, 0) NULL,
    `CreditLimit` DECIMAL(19, 0) NULL,
    `CreditAmount` DECIMAL(19, 0) NULL,
    `PartnerStatus` INTEGER NULL,
    `ApplyToAllCustomer` TINYINT NULL,
    `AttachedDocument` VARCHAR(100) NULL,
    `Partner` CHAR(36) NULL,
    `DiscountForPartner` DOUBLE NULL,
    `OverridePriceFromLandedCost` TINYINT NULL,
    `TermOfPayment` INTEGER NULL,
    `ReceivableAccount` CHAR(36) NULL,
    `Invoiceable` TINYINT NULL,
    `OptimisticLockField` INTEGER NULL,
    `ClaimToId` INTEGER NULL,
    `ClaimTo` VARCHAR(150) NULL,
    `ClaimCategoryId` INTEGER NULL,
    `ClaimCategory` VARCHAR(5) NULL,
    `GCRecord` INTEGER NULL,
    `Branch` VARCHAR(100) NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,

    INDEX `Oid`(`Oid`),
    INDEX `ProgramName`(`ProgramName`),
    PRIMARY KEY (`Oid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `service_repairtype` (
    `RepairTypeId` BIGINT NOT NULL,
    `RepairTypeDescription` VARCHAR(100) NULL,
    `Branch` VARCHAR(100) NULL,
    `OptimisticLockField` INTEGER NULL,
    `GCRecord` INTEGER NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,

    INDEX `RepairTypeId`(`RepairTypeId`),
    PRIMARY KEY (`RepairTypeId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `service_workorder` (
    `GrossJobSales` DECIMAL(19, 0) NULL,
    `GrossPartSales` DECIMAL(19, 0) NULL,
    `TotalPartDiscount` DECIMAL(19, 0) NULL,
    `TotalPartProgram` DECIMAL(19, 0) NULL,
    `TotalPartVAT` DECIMAL(19, 0) NULL,
    `TotalPartWithholdingTax` DECIMAL(19, 0) NULL,
    `TotalJobDiscount` DECIMAL(19, 0) NULL,
    `TotalJobProgram` DECIMAL(19, 0) NULL,
    `TotalJobVAT` DECIMAL(19, 0) NULL,
    `TotalJobWithholdingTax` DECIMAL(19, 0) NULL,
    `TotalJob` DECIMAL(19, 0) NULL,
    `TotalPart` DECIMAL(19, 0) NULL,
    `TotalInvoice` DECIMAL(19, 0) NOT NULL DEFAULT 0,
    `TotalPayment` DECIMAL(19, 0) NULL,
    `DownPayment` DECIMAL(19, 0) NULL,
    `ContraCashAccount` CHAR(36) NULL,
    `Stamp` CHAR(36) NULL,
    `Tax` DECIMAL(19, 0) NULL,
    `ProformaAmount` DECIMAL(19, 0) NULL,
    `ProformaInvoice` VARCHAR(100) NULL,
    `ProformaInvoiceDate` DATETIME(0) NULL,
    `Oid` CHAR(36) NOT NULL,
    `WorkOrderEstimationNo` VARCHAR(100) NULL,
    `WorkOrderEstimationDate` DATETIME(0) NULL,
    `WorkOrderNo` VARCHAR(100) NULL,
    `GatePassId` VARCHAR(100) NULL,
    `WorkOrderDate` DATETIME(0) NULL,
    `CancelDate` DATETIME(0) NULL,
    `CancelReason` VARCHAR(255) NULL,
    `BookingNo` VARCHAR(100) NULL,
    `BookingStartOn` DATETIME(0) NULL,
    `BookingDate` DATETIME(0) NULL,
    `ProspectCategory` CHAR(36) NULL,
    `CustomerType` CHAR(36) NULL,
    `ServiceStartOn` DATETIME(0) NULL,
    `ServiceEndOn` DATETIME(0) NULL,
    `EstimatedFinishTime` DATETIME(0) NULL,
    `BookingMethod` INTEGER NULL,
    `Remark` LONGTEXT NULL,
    `PaymentVia` VARCHAR(100) NULL,
    `Branch` VARCHAR(100) NULL,
    `SourceOfOrder` VARCHAR(100) NULL,
    `IsClockOn` TINYINT NULL,
    `PaymentMethod` INTEGER NULL,
    `BookingStatus` INTEGER NULL,
    `WorkOrderStatus` INTEGER NULL,
    `PRTStatus` BOOLEAN NULL,
    `WorkOrderCompleated` BOOLEAN NOT NULL DEFAULT true,
    `CustomerIsWaiting` TINYINT NULL,
    `EM` TINYINT NULL,
    `SSC` TINYINT NULL,
    `TWC` TINYINT NULL,
    `Insurance` TINYINT NULL,
    `TPSLine` TINYINT NULL,
    `ExternalCustomer` VARCHAR(100) NULL,
    `ExtendedStatus` INTEGER NULL,
    `Washing` TINYINT NULL,
    `CustomerDeliveryDateRequest` DATETIME(0) NULL,
    `RepairSubType` VARCHAR(36) NULL,
    `VehicleUnit` CHAR(36) NULL,
    `CurrentStall` CHAR(36) NULL,
    `ServiceAdvisor` CHAR(36) NULL,
    `Foreman` CHAR(36) NULL,
    `GroupHead` CHAR(36) NULL,
    `Technician` CHAR(100) NULL,
    `BookingStaff` CHAR(36) NULL,
    `RepairType` BIGINT NULL,
    `CustomerFollowUp` CHAR(36) NULL,
    `CustomerFollowUpDate` DATETIME(0) NULL,
    `CustomerFollowUpStatus` CHAR(36) NULL,
    `CustomerFollowUpRemark` VARCHAR(100) NULL,
    `HasBeenRemindedByMRA` TINYINT NULL,
    `FieldAction` CHAR(36) NULL,
    `CarWashQueue` CHAR(36) NULL,
    `QueueNo` INTEGER NULL,
    `FillRate` INTEGER NULL,
    `ServiceInvoice` CHAR(36) NULL,
    `InvoiceDate` DATETIME(0) NULL,
    `AllDay` TINYINT NULL,
    `EndOn` DATETIME(0) NULL,
    `Label` INTEGER NULL,
    `Location` VARCHAR(100) NULL,
    `StartOn` DATETIME(0) NULL,
    `Type` INTEGER NULL,
    `Description` VARCHAR(100) NULL,
    `Sequence` BIGINT NULL,
    `CurrentMileageRecord` INTEGER NULL,
    `DocumentKey` CHAR(36) NULL,
    `IsApproved` TINYINT NULL,
    `OptimisticLockField` INTEGER NULL,
    `GCRecord` INTEGER NULL,
    `DamageCategory` INTEGER NULL,
    `InsuranceWorkOrderId` VARCHAR(100) NULL,
    `ClaimId` VARCHAR(100) NULL,
    `OR` DECIMAL(19, 0) NULL,
    `TotalPartInsurance` DECIMAL(19, 0) NULL,
    `TotalJobInsurance` DECIMAL(19, 0) NULL,
    `CancelOrderReason` CHAR(36) NULL,
    `MobileServiceType` INTEGER NULL,
    `BPCurrentAction` INTEGER NULL,
    `UnsuppliedPart` INTEGER NULL,
    `RepairTypeSummary` VARCHAR(100) NULL,
    `CPUS` TINYINT NULL,
    `OilChangeOnly` TINYINT NULL,
    `EstimatedDeliveryDate` DATETIME(0) NULL,
    `DeliveryDate` DATETIME(0) NULL,
    `ExitPermit` BOOLEAN NOT NULL DEFAULT false,
    `IsPreDiagnose` BOOLEAN NULL,
    `SupplyPartNo` VARCHAR(100) NULL,
    `SupplyPartDate` DATETIME(0) NULL,
    `SPKReference` VARCHAR(100) NULL,
    `PaidDate` DATE NULL,
    `WaitingApproval` CHAR(36) NULL,
    `ApprovalTo` CHAR(36) NULL,
    `StatusApproval` BOOLEAN NOT NULL DEFAULT false,
    `ReasonApproval` VARCHAR(255) NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,
    `CustomerFollowUpFIR` CHAR(1) NULL,
    `CustomerFollowUpFIRRemark` TEXT NULL,
    `CustomerFollowUpFIRDate` DATETIME(0) NULL,
    `CustomerFollowUpFIRBy` INTEGER NULL,
    `CustomerFolloeUpFIRCounterMeasure` TEXT NULL,
    `CustomerFolloeUpFIRStatus` INTEGER NULL,
    `CustomerFolloeUpFIREvidence` VARCHAR(225) NULL,
    `ReSchedule` BOOLEAN NOT NULL DEFAULT false,
    `ClaimNo` VARCHAR(10) NULL,
    `StatusClaim` VARCHAR(50) NULL,
    `Submit` TINYINT NULL,
    `ProcessNo` VARCHAR(20) NULL,
    `Message` TEXT NULL,
    `ErrorCode` CHAR(5) NULL,

    UNIQUE INDEX `WorkOrderNo`(`WorkOrderNo`),
    INDEX `BookingStaff`(`BookingStaff`),
    INDEX `BookingStatus`(`BookingStatus`),
    INDEX `Branch`(`Branch`),
    INDEX `CancelOrderReason`(`CancelOrderReason`),
    INDEX `CarWashQueue`(`CarWashQueue`),
    INDEX `ContraCashAccount`(`ContraCashAccount`),
    INDEX `CurrentMileageRecord`(`CurrentMileageRecord`),
    INDEX `CurrentStall`(`CurrentStall`),
    INDEX `CustomerFollowUp`(`CustomerFollowUp`),
    INDEX `DamageCategory`(`DamageCategory`),
    INDEX `FieldAction`(`FieldAction`),
    INDEX `GCRecord`(`GCRecord`),
    INDEX `GroupHead`(`GroupHead`),
    INDEX `MobileServiceType`(`MobileServiceType`),
    INDEX `Oid`(`Oid`),
    INDEX `RepairSubType`(`RepairSubType`),
    INDEX `RepairType`(`RepairType`),
    INDEX `ServiceAdvisor`(`ServiceAdvisor`),
    INDEX `ServiceInvoice`(`ServiceInvoice`),
    INDEX `SourceOfOrder`(`SourceOfOrder`),
    INDEX `VehicleUnit`(`VehicleUnit`),
    INDEX `WorkOrderDate`(`WorkOrderDate`),
    INDEX `WorkOrderStatus`(`WorkOrderStatus`),
    INDEX `deleted_at`(`deleted_at`),
    PRIMARY KEY (`Oid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `service_workorderpart` (
    `QuantitySupplied` INTEGER NULL,
    `QuantityReject` INTEGER NULL,
    `RejectDate` DATETIME(0) NULL,
    `Oid` CHAR(36) NOT NULL,
    `WorkOrder` CHAR(36) NULL,
    `Job` CHAR(36) NULL,
    `Part` CHAR(36) NULL,
    `Remark` VARCHAR(100) NULL,
    `Quantity` INTEGER NULL,
    `ServiceRate` DOUBLE NULL,
    `UnitPrice` DECIMAL(19, 0) NULL,
    `RetailPrice` DECIMAL(19, 0) NULL,
    `Program` CHAR(36) NULL,
    `DiscountType` CHAR(36) NULL,
    `ProgramName` VARCHAR(100) NULL,
    `ProgramPercentage` DOUBLE NULL,
    `ProgramAmount` DECIMAL(19, 0) NULL,
    `Partner` CHAR(36) NULL,
    `DiscountForPartner` DOUBLE NULL,
    `Discount` CHAR(36) NULL,
    `DiscountName` VARCHAR(100) NULL,
    `DiscountPercentage` DOUBLE NULL,
    `VATCode` CHAR(36) NULL,
    `WithholdingTax` CHAR(36) NULL,
    `Billed` TINYINT NULL,
    `ProgramBilled` TINYINT NULL,
    `PartStatus` INTEGER NULL,
    `PartBooking` INTEGER NULL,
    `ETA` DATETIME(0) NULL,
    `Insurance` CHAR(36) NULL,
    `DiscountForInsurer` DOUBLE NULL,
    `InsuranceName` VARCHAR(100) NULL,
    `InsuranceApproved` TINYINT NULL,
    `PartInsuranceAmount` DECIMAL(19, 0) NULL,
    `OrderProcessed` TINYINT NULL,
    `PartIsPicked` TINYINT NULL,
    `ServicePartBackOrder` CHAR(36) NULL,
    `DiscountApproved` TINYINT NULL,
    `ReservedDate` DATETIME(0) NULL,
    `PickDate` DATETIME(0) NULL,
    `SalesDate` DATETIME(0) NULL,
    `ReturnDate` DATETIME(0) NULL,
    `WaitingApproval` CHAR(30) NULL,
    `StatusApproval` BOOLEAN NULL,
    `SupplySlipDate` DATETIME(0) NULL,
    `SupplySlipNo` VARCHAR(100) NULL,
    `OptimisticLockField` INTEGER NULL,
    `GCRecord` INTEGER NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,

    INDEX `Discount`(`Discount`),
    INDEX `Insurance`(`Insurance`),
    INDEX `Job`(`Job`),
    INDEX `Oid`(`Oid`),
    INDEX `Part`(`Part`),
    INDEX `Program`(`Program`),
    INDEX `ServicePartBackOrder`(`ServicePartBackOrder`),
    INDEX `VATCode`(`VATCode`),
    INDEX `WithholdingTax`(`WithholdingTax`),
    INDEX `WorkOrder`(`WorkOrder`),
    PRIMARY KEY (`Oid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `users` (
    `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ip_address` VARCHAR(45) NULL,
    `username` VARCHAR(100) NOT NULL,
    `password` VARCHAR(80) NOT NULL,
    `email` VARCHAR(254) NOT NULL,
    `activation_selector` VARCHAR(255) NULL,
    `activation_code` VARCHAR(255) NULL,
    `forgotten_password_selector` VARCHAR(255) NULL,
    `forgotten_password_code` VARCHAR(255) NULL,
    `forgotten_password_time` INTEGER UNSIGNED NULL,
    `remember_selector` VARCHAR(255) NULL,
    `remember_code` VARCHAR(255) NULL,
    `created_on` INTEGER UNSIGNED NULL,
    `last_login` INTEGER UNSIGNED NULL,
    `active` TINYINT UNSIGNED NULL,
    `nik` VARCHAR(30) NULL,
    `first_name` VARCHAR(50) NULL,
    `last_name` VARCHAR(50) NULL,
    `company` VARCHAR(100) NULL,
    `phone` VARCHAR(20) NULL,
    `NickName` VARCHAR(100) NULL,
    `Initial` VARCHAR(3) NULL,
    `PreTitle` VARCHAR(100) NULL,
    `PostTitle` VARCHAR(100) NULL,
    `ClothingSize` CHAR(36) NULL,
    `Height` DOUBLE NULL,
    `Weight` DOUBLE NULL,
    `PassportNo` VARCHAR(100) NULL,
    `IssuedAt` VARCHAR(100) NULL,
    `ExpiryDate` DATETIME(0) NULL,
    `IdentificationNo` VARCHAR(100) NULL,
    `IdentificationExpiryDate` DATETIME(0) NULL,
    `TaxRegistrationNo` VARCHAR(100) NULL,
    `PlaceOfBirth` VARCHAR(100) NULL,
    `DateOfBirth` DATE NULL,
    `Gender` CHAR(36) NULL,
    `Ethnic` CHAR(36) NULL,
    `BloodType` CHAR(36) NULL,
    `MaritalStatus` CHAR(36) NULL,
    `MaritalDate` DATETIME(0) NULL,
    `NoOfChildren` SMALLINT NULL,
    `StatusOnTax` INTEGER NULL,
    `DrivingLicenseNo` VARCHAR(100) NULL,
    `DrivingLicenseType` CHAR(36) NULL,
    `Hobby` VARCHAR(100) NULL,
    `Nationality` CHAR(36) NULL,
    `Religion` CHAR(36) NULL,
    `Address1` CHAR(36) NULL,
    `PhoneNo1` VARCHAR(100) NULL,
    `Address2` CHAR(36) NULL,
    `PhoneNo2` VARCHAR(100) NULL,
    `MobileNo1` VARCHAR(100) NULL,
    `MobileNo2` VARCHAR(100) NULL,
    `Email1` VARCHAR(100) NULL,
    `Email2` VARCHAR(100) NULL,
    `MotherName` VARCHAR(50) NULL,
    `EmergencyContactName1` VARCHAR(100) NULL,
    `EmergencyContactRelation1` VARCHAR(100) NULL,
    `EmergencyAddress1` CHAR(36) NULL,
    `EmergencyPhoneNo1` VARCHAR(100) NULL,
    `EmergencyContactName2` VARCHAR(100) NULL,
    `EmergencyContactRelation2` VARCHAR(100) NULL,
    `EmergencyAddress2` CHAR(36) NULL,
    `EmergencyPhoneNo2` VARCHAR(100) NULL,
    `JoinedDate` DATETIME(0) NULL,
    `ConfirmationDate` DATETIME(0) NULL,
    `EmploymentPeriod` INTEGER NULL,
    `ResignDate` DATETIME(0) NULL,
    `LastPromotionDate` DATETIME(0) NULL,
    `SalaryPaymentMethod` CHAR(36) NULL,
    `TaxCalculationMode` INTEGER NULL,
    `OrganizationalUnit` VARCHAR(100) NULL,
    `Branch` VARCHAR(100) NULL,
    `CounterNumber` INTEGER NULL,
    `WorkStatus` INTEGER NULL,
    `Workgroup` CHAR(36) NULL,
    `Grade` CHAR(36) NULL,
    `NonEmployee` TINYINT NULL,
    `AutomaticOvertime` TINYINT NULL,
    `PhoneExt` VARCHAR(100) NULL,
    `PaymentPeriod` INTEGER NULL,
    `EmployeeEducation` CHAR(36) NULL,
    `Qualification` CHAR(36) NULL,
    `GPA` VARCHAR(10) NULL,
    `BankAccountNo` VARCHAR(100) NULL,
    `AccountOwner` VARCHAR(100) NULL,
    `Photo` VARCHAR(100) NULL,
    `PrivateKey` CHAR(36) NULL,
    `IsActive` TINYINT NULL,
    `ChangePasswordOnFirstLogon` TINYINT NULL,
    `StoredPassword` LONGTEXT NULL,
    `SalesForce` CHAR(36) NULL,
    `Technician` CHAR(36) NULL,
    `TechnicianRepairType` VARCHAR(100) NULL,
    `Sequence` BIGINT NULL,
    `EnrollNo` VARCHAR(100) NULL,
    `OptimisticLockField` INTEGER NULL,
    `GCRecord` INTEGER NULL,
    `BankName` CHAR(36) NULL,
    `PersonalGrade` VARCHAR(100) NULL,
    `Homebase` VARCHAR(100) NULL,
    `TechnicianSkill` VARCHAR(11) NULL,
    `Picture` VARCHAR(100) NULL,
    `group_id` VARCHAR(100) NULL,
    `password_expires` DATETIME(0) NULL,
    `ess_user_id` VARCHAR(255) NULL,
    `created_at` DATETIME(0) NULL,
    `user_created` INTEGER NULL,
    `updated_at` DATETIME(0) NULL,
    `user_update` INTEGER NULL,
    `deleted_at` DATETIME(0) NULL,

    INDEX `OrganizationalUnit`(`OrganizationalUnit`),
    INDEX `email`(`email`),
    INDEX `group_id`(`group_id`),
    INDEX `id`(`id`),
    INDEX `password`(`password`),
    INDEX `username`(`username`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
